// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/pdutton/go-interfaces/net/http (interfaces: ClientRequest)
//
// Generated by this command:
//
//	mockgen -destination net/http/mock/client_request.go github.com/pdutton/go-interfaces/net/http ClientRequest
//

// Package mock_http is a generated GoMock package.
package mock_http

import (
	io "io"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockClientRequest is a mock of ClientRequest interface.
type MockClientRequest struct {
	ctrl     *gomock.Controller
	recorder *MockClientRequestMockRecorder
	isgomock struct{}
}

// MockClientRequestMockRecorder is the mock recorder for MockClientRequest.
type MockClientRequestMockRecorder struct {
	mock *MockClientRequest
}

// NewMockClientRequest creates a new mock instance.
func NewMockClientRequest(ctrl *gomock.Controller) *MockClientRequest {
	mock := &MockClientRequest{ctrl: ctrl}
	mock.recorder = &MockClientRequestMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockClientRequest) EXPECT() *MockClientRequestMockRecorder {
	return m.recorder
}

// Write mocks base method.
func (m *MockClientRequest) Write(arg0 io.Writer) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Write", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Write indicates an expected call of Write.
func (mr *MockClientRequestMockRecorder) Write(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Write", reflect.TypeOf((*MockClientRequest)(nil).Write), arg0)
}

// WriteProxy mocks base method.
func (m *MockClientRequest) WriteProxy(arg0 io.Writer) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WriteProxy", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// WriteProxy indicates an expected call of WriteProxy.
func (mr *MockClientRequestMockRecorder) WriteProxy(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WriteProxy", reflect.TypeOf((*MockClientRequest)(nil).WriteProxy), arg0)
}
