// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/pdutton/go-interfaces/net/http (interfaces: HTTP,Client,ClientRequest,ClientResponse,Server)
//
// Generated by this command:
//
//	mockgen -destination net/http/mock_http/all.go github.com/pdutton/go-interfaces/net/http HTTP,Client,ClientRequest,ClientResponse,Server
//

// Package mock_http is a generated GoMock package.
package mock_http

import (
	bufio "bufio"
	context "context"
	tls "crypto/tls"
	io "io"
	fs "io/fs"
	net "net"
	http0 "net/http"
	url "net/url"
	reflect "reflect"
	time "time"

	http "github.com/pdutton/go-interfaces/net/http"
	gomock "go.uber.org/mock/gomock"
)

// MockHTTP is a mock of HTTP interface.
type MockHTTP struct {
	ctrl     *gomock.Controller
	recorder *MockHTTPMockRecorder
	isgomock struct{}
}

// MockHTTPMockRecorder is the mock recorder for MockHTTP.
type MockHTTPMockRecorder struct {
	mock *MockHTTP
}

// NewMockHTTP creates a new mock instance.
func NewMockHTTP(ctrl *gomock.Controller) *MockHTTP {
	mock := &MockHTTP{ctrl: ctrl}
	mock.recorder = &MockHTTPMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockHTTP) EXPECT() *MockHTTPMockRecorder {
	return m.recorder
}

// CanonicalHeaderKey mocks base method.
func (m *MockHTTP) CanonicalHeaderKey(arg0 string) string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CanonicalHeaderKey", arg0)
	ret0, _ := ret[0].(string)
	return ret0
}

// CanonicalHeaderKey indicates an expected call of CanonicalHeaderKey.
func (mr *MockHTTPMockRecorder) CanonicalHeaderKey(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CanonicalHeaderKey", reflect.TypeOf((*MockHTTP)(nil).CanonicalHeaderKey), arg0)
}

// DetectContentType mocks base method.
func (m *MockHTTP) DetectContentType(arg0 []byte) string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DetectContentType", arg0)
	ret0, _ := ret[0].(string)
	return ret0
}

// DetectContentType indicates an expected call of DetectContentType.
func (mr *MockHTTPMockRecorder) DetectContentType(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DetectContentType", reflect.TypeOf((*MockHTTP)(nil).DetectContentType), arg0)
}

// Error mocks base method.
func (m *MockHTTP) Error(arg0 http0.ResponseWriter, arg1 string, arg2 int) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Error", arg0, arg1, arg2)
}

// Error indicates an expected call of Error.
func (mr *MockHTTPMockRecorder) Error(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Error", reflect.TypeOf((*MockHTTP)(nil).Error), arg0, arg1, arg2)
}

// Get mocks base method.
func (m *MockHTTP) Get(arg0 string) (http.ClientResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", arg0)
	ret0, _ := ret[0].(http.ClientResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockHTTPMockRecorder) Get(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockHTTP)(nil).Get), arg0)
}

// Handle mocks base method.
func (m *MockHTTP) Handle(arg0 string, arg1 http0.Handler) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Handle", arg0, arg1)
}

// Handle indicates an expected call of Handle.
func (mr *MockHTTPMockRecorder) Handle(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Handle", reflect.TypeOf((*MockHTTP)(nil).Handle), arg0, arg1)
}

// HandleFunc mocks base method.
func (m *MockHTTP) HandleFunc(arg0 string, arg1 func(http0.ResponseWriter, *http0.Request)) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "HandleFunc", arg0, arg1)
}

// HandleFunc indicates an expected call of HandleFunc.
func (mr *MockHTTPMockRecorder) HandleFunc(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HandleFunc", reflect.TypeOf((*MockHTTP)(nil).HandleFunc), arg0, arg1)
}

// Head mocks base method.
func (m *MockHTTP) Head(arg0 string) (http.ClientResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Head", arg0)
	ret0, _ := ret[0].(http.ClientResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Head indicates an expected call of Head.
func (mr *MockHTTPMockRecorder) Head(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Head", reflect.TypeOf((*MockHTTP)(nil).Head), arg0)
}

// ListenAndServe mocks base method.
func (m *MockHTTP) ListenAndServe(arg0 string, arg1 http0.Handler) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListenAndServe", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// ListenAndServe indicates an expected call of ListenAndServe.
func (mr *MockHTTPMockRecorder) ListenAndServe(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListenAndServe", reflect.TypeOf((*MockHTTP)(nil).ListenAndServe), arg0, arg1)
}

// ListenAndServeTLS mocks base method.
func (m *MockHTTP) ListenAndServeTLS(arg0, arg1, arg2 string, arg3 http0.Handler) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListenAndServeTLS", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(error)
	return ret0
}

// ListenAndServeTLS indicates an expected call of ListenAndServeTLS.
func (mr *MockHTTPMockRecorder) ListenAndServeTLS(arg0, arg1, arg2, arg3 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListenAndServeTLS", reflect.TypeOf((*MockHTTP)(nil).ListenAndServeTLS), arg0, arg1, arg2, arg3)
}

// MaxBytesReader mocks base method.
func (m *MockHTTP) MaxBytesReader(arg0 http0.ResponseWriter, arg1 io.ReadCloser, arg2 int64) io.ReadCloser {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MaxBytesReader", arg0, arg1, arg2)
	ret0, _ := ret[0].(io.ReadCloser)
	return ret0
}

// MaxBytesReader indicates an expected call of MaxBytesReader.
func (mr *MockHTTPMockRecorder) MaxBytesReader(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MaxBytesReader", reflect.TypeOf((*MockHTTP)(nil).MaxBytesReader), arg0, arg1, arg2)
}

// NotFound mocks base method.
func (m *MockHTTP) NotFound(arg0 http0.ResponseWriter, arg1 *http0.Request) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "NotFound", arg0, arg1)
}

// NotFound indicates an expected call of NotFound.
func (mr *MockHTTPMockRecorder) NotFound(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NotFound", reflect.TypeOf((*MockHTTP)(nil).NotFound), arg0, arg1)
}

// ParseHTTPVersion mocks base method.
func (m *MockHTTP) ParseHTTPVersion(arg0 string) (int, int, bool) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ParseHTTPVersion", arg0)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(bool)
	return ret0, ret1, ret2
}

// ParseHTTPVersion indicates an expected call of ParseHTTPVersion.
func (mr *MockHTTPMockRecorder) ParseHTTPVersion(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ParseHTTPVersion", reflect.TypeOf((*MockHTTP)(nil).ParseHTTPVersion), arg0)
}

// ParseTime mocks base method.
func (m *MockHTTP) ParseTime(arg0 string) (time.Time, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ParseTime", arg0)
	ret0, _ := ret[0].(time.Time)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ParseTime indicates an expected call of ParseTime.
func (mr *MockHTTPMockRecorder) ParseTime(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ParseTime", reflect.TypeOf((*MockHTTP)(nil).ParseTime), arg0)
}

// Post mocks base method.
func (m *MockHTTP) Post(arg0, arg1 string, arg2 io.Reader) (http.ClientResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Post", arg0, arg1, arg2)
	ret0, _ := ret[0].(http.ClientResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Post indicates an expected call of Post.
func (mr *MockHTTPMockRecorder) Post(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Post", reflect.TypeOf((*MockHTTP)(nil).Post), arg0, arg1, arg2)
}

// PostForm mocks base method.
func (m *MockHTTP) PostForm(arg0 string, arg1 url.Values) (http.ClientResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PostForm", arg0, arg1)
	ret0, _ := ret[0].(http.ClientResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PostForm indicates an expected call of PostForm.
func (mr *MockHTTPMockRecorder) PostForm(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PostForm", reflect.TypeOf((*MockHTTP)(nil).PostForm), arg0, arg1)
}

// ProxyFromEnvironment mocks base method.
func (m *MockHTTP) ProxyFromEnvironment(arg0 *http0.Request) (*url.URL, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ProxyFromEnvironment", arg0)
	ret0, _ := ret[0].(*url.URL)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ProxyFromEnvironment indicates an expected call of ProxyFromEnvironment.
func (mr *MockHTTPMockRecorder) ProxyFromEnvironment(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ProxyFromEnvironment", reflect.TypeOf((*MockHTTP)(nil).ProxyFromEnvironment), arg0)
}

// ProxyURL mocks base method.
func (m *MockHTTP) ProxyURL(arg0 *url.URL) func(*http0.Request) (*url.URL, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ProxyURL", arg0)
	ret0, _ := ret[0].(func(*http0.Request) (*url.URL, error))
	return ret0
}

// ProxyURL indicates an expected call of ProxyURL.
func (mr *MockHTTPMockRecorder) ProxyURL(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ProxyURL", reflect.TypeOf((*MockHTTP)(nil).ProxyURL), arg0)
}

// ReadResponse mocks base method.
func (m *MockHTTP) ReadResponse(arg0 *bufio.Reader, arg1 *http0.Request) (http.ClientResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReadResponse", arg0, arg1)
	ret0, _ := ret[0].(http.ClientResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReadResponse indicates an expected call of ReadResponse.
func (mr *MockHTTPMockRecorder) ReadResponse(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReadResponse", reflect.TypeOf((*MockHTTP)(nil).ReadResponse), arg0, arg1)
}

// Redirect mocks base method.
func (m *MockHTTP) Redirect(arg0 http0.ResponseWriter, arg1 *http0.Request, arg2 string, arg3 int) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Redirect", arg0, arg1, arg2, arg3)
}

// Redirect indicates an expected call of Redirect.
func (mr *MockHTTPMockRecorder) Redirect(arg0, arg1, arg2, arg3 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Redirect", reflect.TypeOf((*MockHTTP)(nil).Redirect), arg0, arg1, arg2, arg3)
}

// Serve mocks base method.
func (m *MockHTTP) Serve(arg0 net.Listener, arg1 http0.Handler) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Serve", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Serve indicates an expected call of Serve.
func (mr *MockHTTPMockRecorder) Serve(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Serve", reflect.TypeOf((*MockHTTP)(nil).Serve), arg0, arg1)
}

// ServeContent mocks base method.
func (m *MockHTTP) ServeContent(arg0 http0.ResponseWriter, arg1 *http0.Request, arg2 string, arg3 time.Time, arg4 io.ReadSeeker) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "ServeContent", arg0, arg1, arg2, arg3, arg4)
}

// ServeContent indicates an expected call of ServeContent.
func (mr *MockHTTPMockRecorder) ServeContent(arg0, arg1, arg2, arg3, arg4 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ServeContent", reflect.TypeOf((*MockHTTP)(nil).ServeContent), arg0, arg1, arg2, arg3, arg4)
}

// ServeFile mocks base method.
func (m *MockHTTP) ServeFile(arg0 http0.ResponseWriter, arg1 *http0.Request, arg2 string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "ServeFile", arg0, arg1, arg2)
}

// ServeFile indicates an expected call of ServeFile.
func (mr *MockHTTPMockRecorder) ServeFile(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ServeFile", reflect.TypeOf((*MockHTTP)(nil).ServeFile), arg0, arg1, arg2)
}

// ServeFileFS mocks base method.
func (m *MockHTTP) ServeFileFS(arg0 http0.ResponseWriter, arg1 *http0.Request, arg2 fs.FS, arg3 string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "ServeFileFS", arg0, arg1, arg2, arg3)
}

// ServeFileFS indicates an expected call of ServeFileFS.
func (mr *MockHTTPMockRecorder) ServeFileFS(arg0, arg1, arg2, arg3 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ServeFileFS", reflect.TypeOf((*MockHTTP)(nil).ServeFileFS), arg0, arg1, arg2, arg3)
}

// ServeTLS mocks base method.
func (m *MockHTTP) ServeTLS(arg0 net.Listener, arg1 http0.Handler, arg2, arg3 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ServeTLS", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(error)
	return ret0
}

// ServeTLS indicates an expected call of ServeTLS.
func (mr *MockHTTPMockRecorder) ServeTLS(arg0, arg1, arg2, arg3 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ServeTLS", reflect.TypeOf((*MockHTTP)(nil).ServeTLS), arg0, arg1, arg2, arg3)
}

// SetCookie mocks base method.
func (m *MockHTTP) SetCookie(arg0 http0.ResponseWriter, arg1 *http0.Cookie) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetCookie", arg0, arg1)
}

// SetCookie indicates an expected call of SetCookie.
func (mr *MockHTTPMockRecorder) SetCookie(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetCookie", reflect.TypeOf((*MockHTTP)(nil).SetCookie), arg0, arg1)
}

// StatusText mocks base method.
func (m *MockHTTP) StatusText(arg0 int) string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StatusText", arg0)
	ret0, _ := ret[0].(string)
	return ret0
}

// StatusText indicates an expected call of StatusText.
func (mr *MockHTTPMockRecorder) StatusText(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StatusText", reflect.TypeOf((*MockHTTP)(nil).StatusText), arg0)
}

// MockClient is a mock of Client interface.
type MockClient struct {
	ctrl     *gomock.Controller
	recorder *MockClientMockRecorder
	isgomock struct{}
}

// MockClientMockRecorder is the mock recorder for MockClient.
type MockClientMockRecorder struct {
	mock *MockClient
}

// NewMockClient creates a new mock instance.
func NewMockClient(ctrl *gomock.Controller) *MockClient {
	mock := &MockClient{ctrl: ctrl}
	mock.recorder = &MockClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockClient) EXPECT() *MockClientMockRecorder {
	return m.recorder
}

// CloseIdleConnections mocks base method.
func (m *MockClient) CloseIdleConnections() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "CloseIdleConnections")
}

// CloseIdleConnections indicates an expected call of CloseIdleConnections.
func (mr *MockClientMockRecorder) CloseIdleConnections() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CloseIdleConnections", reflect.TypeOf((*MockClient)(nil).CloseIdleConnections))
}

// Do mocks base method.
func (m *MockClient) Do(arg0 *http0.Request) (http.ClientResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Do", arg0)
	ret0, _ := ret[0].(http.ClientResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Do indicates an expected call of Do.
func (mr *MockClientMockRecorder) Do(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Do", reflect.TypeOf((*MockClient)(nil).Do), arg0)
}

// Get mocks base method.
func (m *MockClient) Get(arg0 string) (http.ClientResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", arg0)
	ret0, _ := ret[0].(http.ClientResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockClientMockRecorder) Get(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockClient)(nil).Get), arg0)
}

// Head mocks base method.
func (m *MockClient) Head(arg0 string) (http.ClientResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Head", arg0)
	ret0, _ := ret[0].(http.ClientResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Head indicates an expected call of Head.
func (mr *MockClientMockRecorder) Head(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Head", reflect.TypeOf((*MockClient)(nil).Head), arg0)
}

// Post mocks base method.
func (m *MockClient) Post(arg0, arg1 string, arg2 io.Reader) (http.ClientResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Post", arg0, arg1, arg2)
	ret0, _ := ret[0].(http.ClientResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Post indicates an expected call of Post.
func (mr *MockClientMockRecorder) Post(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Post", reflect.TypeOf((*MockClient)(nil).Post), arg0, arg1, arg2)
}

// PostForm mocks base method.
func (m *MockClient) PostForm(arg0 string, arg1 url.Values) (http.ClientResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PostForm", arg0, arg1)
	ret0, _ := ret[0].(http.ClientResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PostForm indicates an expected call of PostForm.
func (mr *MockClientMockRecorder) PostForm(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PostForm", reflect.TypeOf((*MockClient)(nil).PostForm), arg0, arg1)
}

// MockClientRequest is a mock of ClientRequest interface.
type MockClientRequest struct {
	ctrl     *gomock.Controller
	recorder *MockClientRequestMockRecorder
	isgomock struct{}
}

// MockClientRequestMockRecorder is the mock recorder for MockClientRequest.
type MockClientRequestMockRecorder struct {
	mock *MockClientRequest
}

// NewMockClientRequest creates a new mock instance.
func NewMockClientRequest(ctrl *gomock.Controller) *MockClientRequest {
	mock := &MockClientRequest{ctrl: ctrl}
	mock.recorder = &MockClientRequestMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockClientRequest) EXPECT() *MockClientRequestMockRecorder {
	return m.recorder
}

// Write mocks base method.
func (m *MockClientRequest) Write(arg0 io.Writer) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Write", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Write indicates an expected call of Write.
func (mr *MockClientRequestMockRecorder) Write(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Write", reflect.TypeOf((*MockClientRequest)(nil).Write), arg0)
}

// WriteProxy mocks base method.
func (m *MockClientRequest) WriteProxy(arg0 io.Writer) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WriteProxy", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// WriteProxy indicates an expected call of WriteProxy.
func (mr *MockClientRequestMockRecorder) WriteProxy(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WriteProxy", reflect.TypeOf((*MockClientRequest)(nil).WriteProxy), arg0)
}

// MockClientResponse is a mock of ClientResponse interface.
type MockClientResponse struct {
	ctrl     *gomock.Controller
	recorder *MockClientResponseMockRecorder
	isgomock struct{}
}

// MockClientResponseMockRecorder is the mock recorder for MockClientResponse.
type MockClientResponseMockRecorder struct {
	mock *MockClientResponse
}

// NewMockClientResponse creates a new mock instance.
func NewMockClientResponse(ctrl *gomock.Controller) *MockClientResponse {
	mock := &MockClientResponse{ctrl: ctrl}
	mock.recorder = &MockClientResponseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockClientResponse) EXPECT() *MockClientResponseMockRecorder {
	return m.recorder
}

// Body mocks base method.
func (m *MockClientResponse) Body() io.ReadCloser {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Body")
	ret0, _ := ret[0].(io.ReadCloser)
	return ret0
}

// Body indicates an expected call of Body.
func (mr *MockClientResponseMockRecorder) Body() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Body", reflect.TypeOf((*MockClientResponse)(nil).Body))
}

// Close mocks base method.
func (m *MockClientResponse) Close() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close")
	ret0, _ := ret[0].(bool)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *MockClientResponseMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockClientResponse)(nil).Close))
}

// ContentLength mocks base method.
func (m *MockClientResponse) ContentLength() int64 {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ContentLength")
	ret0, _ := ret[0].(int64)
	return ret0
}

// ContentLength indicates an expected call of ContentLength.
func (mr *MockClientResponseMockRecorder) ContentLength() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ContentLength", reflect.TypeOf((*MockClientResponse)(nil).ContentLength))
}

// Cookies mocks base method.
func (m *MockClientResponse) Cookies() []*http0.Cookie {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Cookies")
	ret0, _ := ret[0].([]*http0.Cookie)
	return ret0
}

// Cookies indicates an expected call of Cookies.
func (mr *MockClientResponseMockRecorder) Cookies() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Cookies", reflect.TypeOf((*MockClientResponse)(nil).Cookies))
}

// Header mocks base method.
func (m *MockClientResponse) Header() http0.Header {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Header")
	ret0, _ := ret[0].(http0.Header)
	return ret0
}

// Header indicates an expected call of Header.
func (mr *MockClientResponseMockRecorder) Header() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Header", reflect.TypeOf((*MockClientResponse)(nil).Header))
}

// Location mocks base method.
func (m *MockClientResponse) Location() (*url.URL, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Location")
	ret0, _ := ret[0].(*url.URL)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Location indicates an expected call of Location.
func (mr *MockClientResponseMockRecorder) Location() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Location", reflect.TypeOf((*MockClientResponse)(nil).Location))
}

// Proto mocks base method.
func (m *MockClientResponse) Proto() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Proto")
	ret0, _ := ret[0].(string)
	return ret0
}

// Proto indicates an expected call of Proto.
func (mr *MockClientResponseMockRecorder) Proto() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Proto", reflect.TypeOf((*MockClientResponse)(nil).Proto))
}

// ProtoAtLeast mocks base method.
func (m *MockClientResponse) ProtoAtLeast(arg0, arg1 int) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ProtoAtLeast", arg0, arg1)
	ret0, _ := ret[0].(bool)
	return ret0
}

// ProtoAtLeast indicates an expected call of ProtoAtLeast.
func (mr *MockClientResponseMockRecorder) ProtoAtLeast(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ProtoAtLeast", reflect.TypeOf((*MockClientResponse)(nil).ProtoAtLeast), arg0, arg1)
}

// ProtoMajor mocks base method.
func (m *MockClientResponse) ProtoMajor() int {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ProtoMajor")
	ret0, _ := ret[0].(int)
	return ret0
}

// ProtoMajor indicates an expected call of ProtoMajor.
func (mr *MockClientResponseMockRecorder) ProtoMajor() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ProtoMajor", reflect.TypeOf((*MockClientResponse)(nil).ProtoMajor))
}

// ProtoMinor mocks base method.
func (m *MockClientResponse) ProtoMinor() int {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ProtoMinor")
	ret0, _ := ret[0].(int)
	return ret0
}

// ProtoMinor indicates an expected call of ProtoMinor.
func (mr *MockClientResponseMockRecorder) ProtoMinor() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ProtoMinor", reflect.TypeOf((*MockClientResponse)(nil).ProtoMinor))
}

// Request mocks base method.
func (m *MockClientResponse) Request() http.ClientRequest {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Request")
	ret0, _ := ret[0].(http.ClientRequest)
	return ret0
}

// Request indicates an expected call of Request.
func (mr *MockClientResponseMockRecorder) Request() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Request", reflect.TypeOf((*MockClientResponse)(nil).Request))
}

// Status mocks base method.
func (m *MockClientResponse) Status() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Status")
	ret0, _ := ret[0].(string)
	return ret0
}

// Status indicates an expected call of Status.
func (mr *MockClientResponseMockRecorder) Status() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Status", reflect.TypeOf((*MockClientResponse)(nil).Status))
}

// StatusCode mocks base method.
func (m *MockClientResponse) StatusCode() int {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StatusCode")
	ret0, _ := ret[0].(int)
	return ret0
}

// StatusCode indicates an expected call of StatusCode.
func (mr *MockClientResponseMockRecorder) StatusCode() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StatusCode", reflect.TypeOf((*MockClientResponse)(nil).StatusCode))
}

// TLS mocks base method.
func (m *MockClientResponse) TLS() *tls.ConnectionState {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TLS")
	ret0, _ := ret[0].(*tls.ConnectionState)
	return ret0
}

// TLS indicates an expected call of TLS.
func (mr *MockClientResponseMockRecorder) TLS() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TLS", reflect.TypeOf((*MockClientResponse)(nil).TLS))
}

// Trailer mocks base method.
func (m *MockClientResponse) Trailer() http0.Header {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Trailer")
	ret0, _ := ret[0].(http0.Header)
	return ret0
}

// Trailer indicates an expected call of Trailer.
func (mr *MockClientResponseMockRecorder) Trailer() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Trailer", reflect.TypeOf((*MockClientResponse)(nil).Trailer))
}

// TransferEncoding mocks base method.
func (m *MockClientResponse) TransferEncoding() []string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TransferEncoding")
	ret0, _ := ret[0].([]string)
	return ret0
}

// TransferEncoding indicates an expected call of TransferEncoding.
func (mr *MockClientResponseMockRecorder) TransferEncoding() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TransferEncoding", reflect.TypeOf((*MockClientResponse)(nil).TransferEncoding))
}

// Uncompressed mocks base method.
func (m *MockClientResponse) Uncompressed() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Uncompressed")
	ret0, _ := ret[0].(bool)
	return ret0
}

// Uncompressed indicates an expected call of Uncompressed.
func (mr *MockClientResponseMockRecorder) Uncompressed() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Uncompressed", reflect.TypeOf((*MockClientResponse)(nil).Uncompressed))
}

// Write mocks base method.
func (m *MockClientResponse) Write(arg0 io.Writer) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Write", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Write indicates an expected call of Write.
func (mr *MockClientResponseMockRecorder) Write(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Write", reflect.TypeOf((*MockClientResponse)(nil).Write), arg0)
}

// MockServer is a mock of Server interface.
type MockServer struct {
	ctrl     *gomock.Controller
	recorder *MockServerMockRecorder
	isgomock struct{}
}

// MockServerMockRecorder is the mock recorder for MockServer.
type MockServerMockRecorder struct {
	mock *MockServer
}

// NewMockServer creates a new mock instance.
func NewMockServer(ctrl *gomock.Controller) *MockServer {
	mock := &MockServer{ctrl: ctrl}
	mock.recorder = &MockServerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockServer) EXPECT() *MockServerMockRecorder {
	return m.recorder
}

// Close mocks base method.
func (m *MockServer) Close() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close")
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *MockServerMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockServer)(nil).Close))
}

// ListenAndServe mocks base method.
func (m *MockServer) ListenAndServe() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListenAndServe")
	ret0, _ := ret[0].(error)
	return ret0
}

// ListenAndServe indicates an expected call of ListenAndServe.
func (mr *MockServerMockRecorder) ListenAndServe() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListenAndServe", reflect.TypeOf((*MockServer)(nil).ListenAndServe))
}

// ListenAndServeTLS mocks base method.
func (m *MockServer) ListenAndServeTLS(arg0, arg1 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListenAndServeTLS", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// ListenAndServeTLS indicates an expected call of ListenAndServeTLS.
func (mr *MockServerMockRecorder) ListenAndServeTLS(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListenAndServeTLS", reflect.TypeOf((*MockServer)(nil).ListenAndServeTLS), arg0, arg1)
}

// RegisterOnShutdown mocks base method.
func (m *MockServer) RegisterOnShutdown(arg0 func()) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "RegisterOnShutdown", arg0)
}

// RegisterOnShutdown indicates an expected call of RegisterOnShutdown.
func (mr *MockServerMockRecorder) RegisterOnShutdown(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RegisterOnShutdown", reflect.TypeOf((*MockServer)(nil).RegisterOnShutdown), arg0)
}

// Serve mocks base method.
func (m *MockServer) Serve(arg0 net.Listener) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Serve", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Serve indicates an expected call of Serve.
func (mr *MockServerMockRecorder) Serve(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Serve", reflect.TypeOf((*MockServer)(nil).Serve), arg0)
}

// ServeTLS mocks base method.
func (m *MockServer) ServeTLS(arg0 net.Listener, arg1, arg2 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ServeTLS", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// ServeTLS indicates an expected call of ServeTLS.
func (mr *MockServerMockRecorder) ServeTLS(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ServeTLS", reflect.TypeOf((*MockServer)(nil).ServeTLS), arg0, arg1, arg2)
}

// SetKeepAlivesEnabled mocks base method.
func (m *MockServer) SetKeepAlivesEnabled(arg0 bool) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetKeepAlivesEnabled", arg0)
}

// SetKeepAlivesEnabled indicates an expected call of SetKeepAlivesEnabled.
func (mr *MockServerMockRecorder) SetKeepAlivesEnabled(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetKeepAlivesEnabled", reflect.TypeOf((*MockServer)(nil).SetKeepAlivesEnabled), arg0)
}

// Shutdown mocks base method.
func (m *MockServer) Shutdown(arg0 context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Shutdown", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Shutdown indicates an expected call of Shutdown.
func (mr *MockServerMockRecorder) Shutdown(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Shutdown", reflect.TypeOf((*MockServer)(nil).Shutdown), arg0)
}
