// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/pdutton/go-interfaces/encoding/json (interfaces: JSON,Decoder,Encoder)
//
// Generated by this command:
//
//	mockgen -destination encoding/json/mock_json/all.go -package mock_json github.com/pdutton/go-interfaces/encoding/json JSON,Decoder,Encoder
//

// Package mock_json is a generated GoMock package.
package mock_json

import (
	bytes "bytes"
	json "encoding/json"
	io "io"
	reflect "reflect"

	json0 "github.com/pdutton/go-interfaces/encoding/json"
	gomock "go.uber.org/mock/gomock"
)

// MockJSON is a mock of JSON interface.
type MockJSON struct {
	ctrl     *gomock.Controller
	recorder *MockJSONMockRecorder
	isgomock struct{}
}

// MockJSONMockRecorder is the mock recorder for MockJSON.
type MockJSONMockRecorder struct {
	mock *MockJSON
}

// NewMockJSON creates a new mock instance.
func NewMockJSON(ctrl *gomock.Controller) *MockJSON {
	mock := &MockJSON{ctrl: ctrl}
	mock.recorder = &MockJSONMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockJSON) EXPECT() *MockJSONMockRecorder {
	return m.recorder
}

// Compact mocks base method.
func (m *MockJSON) Compact(dst *bytes.Buffer, src []byte) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Compact", dst, src)
	ret0, _ := ret[0].(error)
	return ret0
}

// Compact indicates an expected call of Compact.
func (mr *MockJSONMockRecorder) Compact(dst, src any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Compact", reflect.TypeOf((*MockJSON)(nil).Compact), dst, src)
}

// HTMLEscape mocks base method.
func (m *MockJSON) HTMLEscape(dst *bytes.Buffer, src []byte) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "HTMLEscape", dst, src)
}

// HTMLEscape indicates an expected call of HTMLEscape.
func (mr *MockJSONMockRecorder) HTMLEscape(dst, src any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HTMLEscape", reflect.TypeOf((*MockJSON)(nil).HTMLEscape), dst, src)
}

// Indent mocks base method.
func (m *MockJSON) Indent(dst *bytes.Buffer, src []byte, prefix, indent string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Indent", dst, src, prefix, indent)
	ret0, _ := ret[0].(error)
	return ret0
}

// Indent indicates an expected call of Indent.
func (mr *MockJSONMockRecorder) Indent(dst, src, prefix, indent any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Indent", reflect.TypeOf((*MockJSON)(nil).Indent), dst, src, prefix, indent)
}

// Marshal mocks base method.
func (m *MockJSON) Marshal(v any) ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Marshal", v)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Marshal indicates an expected call of Marshal.
func (mr *MockJSONMockRecorder) Marshal(v any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Marshal", reflect.TypeOf((*MockJSON)(nil).Marshal), v)
}

// MarshalIndent mocks base method.
func (m *MockJSON) MarshalIndent(v any, prefix, indent string) ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarshalIndent", v, prefix, indent)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// MarshalIndent indicates an expected call of MarshalIndent.
func (mr *MockJSONMockRecorder) MarshalIndent(v, prefix, indent any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarshalIndent", reflect.TypeOf((*MockJSON)(nil).MarshalIndent), v, prefix, indent)
}

// NewDecoder mocks base method.
func (m *MockJSON) NewDecoder(r io.Reader, options ...json0.DecoderOption) json0.Decoder {
	m.ctrl.T.Helper()
	varargs := []any{r}
	for _, a := range options {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "NewDecoder", varargs...)
	ret0, _ := ret[0].(json0.Decoder)
	return ret0
}

// NewDecoder indicates an expected call of NewDecoder.
func (mr *MockJSONMockRecorder) NewDecoder(r any, options ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{r}, options...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewDecoder", reflect.TypeOf((*MockJSON)(nil).NewDecoder), varargs...)
}

// NewEncoder mocks base method.
func (m *MockJSON) NewEncoder(w io.Writer, options ...json0.EncoderOption) json0.Encoder {
	m.ctrl.T.Helper()
	varargs := []any{w}
	for _, a := range options {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "NewEncoder", varargs...)
	ret0, _ := ret[0].(json0.Encoder)
	return ret0
}

// NewEncoder indicates an expected call of NewEncoder.
func (mr *MockJSONMockRecorder) NewEncoder(w any, options ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{w}, options...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewEncoder", reflect.TypeOf((*MockJSON)(nil).NewEncoder), varargs...)
}

// Unmarshal mocks base method.
func (m *MockJSON) Unmarshal(data []byte, v any) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Unmarshal", data, v)
	ret0, _ := ret[0].(error)
	return ret0
}

// Unmarshal indicates an expected call of Unmarshal.
func (mr *MockJSONMockRecorder) Unmarshal(data, v any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Unmarshal", reflect.TypeOf((*MockJSON)(nil).Unmarshal), data, v)
}

// Valid mocks base method.
func (m *MockJSON) Valid(data []byte) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Valid", data)
	ret0, _ := ret[0].(bool)
	return ret0
}

// Valid indicates an expected call of Valid.
func (mr *MockJSONMockRecorder) Valid(data any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Valid", reflect.TypeOf((*MockJSON)(nil).Valid), data)
}

// MockDecoder is a mock of Decoder interface.
type MockDecoder struct {
	ctrl     *gomock.Controller
	recorder *MockDecoderMockRecorder
	isgomock struct{}
}

// MockDecoderMockRecorder is the mock recorder for MockDecoder.
type MockDecoderMockRecorder struct {
	mock *MockDecoder
}

// NewMockDecoder creates a new mock instance.
func NewMockDecoder(ctrl *gomock.Controller) *MockDecoder {
	mock := &MockDecoder{ctrl: ctrl}
	mock.recorder = &MockDecoderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDecoder) EXPECT() *MockDecoderMockRecorder {
	return m.recorder
}

// Buffered mocks base method.
func (m *MockDecoder) Buffered() io.Reader {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Buffered")
	ret0, _ := ret[0].(io.Reader)
	return ret0
}

// Buffered indicates an expected call of Buffered.
func (mr *MockDecoderMockRecorder) Buffered() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Buffered", reflect.TypeOf((*MockDecoder)(nil).Buffered))
}

// Decode mocks base method.
func (m *MockDecoder) Decode(v any) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Decode", v)
	ret0, _ := ret[0].(error)
	return ret0
}

// Decode indicates an expected call of Decode.
func (mr *MockDecoderMockRecorder) Decode(v any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Decode", reflect.TypeOf((*MockDecoder)(nil).Decode), v)
}

// InputOffset mocks base method.
func (m *MockDecoder) InputOffset() int64 {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InputOffset")
	ret0, _ := ret[0].(int64)
	return ret0
}

// InputOffset indicates an expected call of InputOffset.
func (mr *MockDecoderMockRecorder) InputOffset() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InputOffset", reflect.TypeOf((*MockDecoder)(nil).InputOffset))
}

// More mocks base method.
func (m *MockDecoder) More() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "More")
	ret0, _ := ret[0].(bool)
	return ret0
}

// More indicates an expected call of More.
func (mr *MockDecoderMockRecorder) More() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "More", reflect.TypeOf((*MockDecoder)(nil).More))
}

// Nub mocks base method.
func (m *MockDecoder) Nub() *json.Decoder {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Nub")
	ret0, _ := ret[0].(*json.Decoder)
	return ret0
}

// Nub indicates an expected call of Nub.
func (mr *MockDecoderMockRecorder) Nub() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Nub", reflect.TypeOf((*MockDecoder)(nil).Nub))
}

// Token mocks base method.
func (m *MockDecoder) Token() (json.Token, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Token")
	ret0, _ := ret[0].(json.Token)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Token indicates an expected call of Token.
func (mr *MockDecoderMockRecorder) Token() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Token", reflect.TypeOf((*MockDecoder)(nil).Token))
}

// MockEncoder is a mock of Encoder interface.
type MockEncoder struct {
	ctrl     *gomock.Controller
	recorder *MockEncoderMockRecorder
	isgomock struct{}
}

// MockEncoderMockRecorder is the mock recorder for MockEncoder.
type MockEncoderMockRecorder struct {
	mock *MockEncoder
}

// NewMockEncoder creates a new mock instance.
func NewMockEncoder(ctrl *gomock.Controller) *MockEncoder {
	mock := &MockEncoder{ctrl: ctrl}
	mock.recorder = &MockEncoderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEncoder) EXPECT() *MockEncoderMockRecorder {
	return m.recorder
}

// Encode mocks base method.
func (m *MockEncoder) Encode(v any) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Encode", v)
	ret0, _ := ret[0].(error)
	return ret0
}

// Encode indicates an expected call of Encode.
func (mr *MockEncoderMockRecorder) Encode(v any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Encode", reflect.TypeOf((*MockEncoder)(nil).Encode), v)
}

// Nub mocks base method.
func (m *MockEncoder) Nub() *json.Encoder {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Nub")
	ret0, _ := ret[0].(*json.Encoder)
	return ret0
}

// Nub indicates an expected call of Nub.
func (mr *MockEncoderMockRecorder) Nub() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Nub", reflect.TypeOf((*MockEncoder)(nil).Nub))
}

// SetEscapeHTML mocks base method.
func (m *MockEncoder) SetEscapeHTML(on bool) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetEscapeHTML", on)
}

// SetEscapeHTML indicates an expected call of SetEscapeHTML.
func (mr *MockEncoderMockRecorder) SetEscapeHTML(on any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetEscapeHTML", reflect.TypeOf((*MockEncoder)(nil).SetEscapeHTML), on)
}

// SetIndent mocks base method.
func (m *MockEncoder) SetIndent(prefix, indent string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetIndent", prefix, indent)
}

// SetIndent indicates an expected call of SetIndent.
func (mr *MockEncoderMockRecorder) SetIndent(prefix, indent any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetIndent", reflect.TypeOf((*MockEncoder)(nil).SetIndent), prefix, indent)
}
